language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: e3NcJbgf4E9+yerQnLQYJ4dJNTtaaiDpCdG4Ig2LBsuPVw731n+b7SPMgLplBuip2oWmrKcjzxXq/ZESgLwAj9Q2hHXw/VyPRkY4j6jwC3nMAgtR9BqtMpOrt2VRjVKFd5K0JLnqL55Yf95rZ3FWUwH0rufo7DxGgeoLAYfX0zbH5QQSEsAgc6VpxVieMv7aoKpCQOGfQBDeS4q/1QzpUWlISvZD/ZXDCmxcCthrCheBm+TH0g7UzY+gz5Y1Pcn3aP9YasoVzsLaLNDl4YGCSCENEZYAsPjmdI6WAtzRRjPYHPniATD3oT14gL3CBHf5DyuckvQQMKZRVdK6ic+UOeR0Fko+RIIGsWWLgQp4cZ3V1wr/afUs3E2hwV7FV8fMuEz7zoK8ygIpusTCtbFLKfqEoUwFsr67+KJKGgubnt74UQuL3wB5mMlp4aoE9eyLfv1AKxWWakAMCdyzl6jhRgqSjIyLI/H3DVolrmqcFk7juam5H3KNUJ5M+kZ0DxmNfO8fe8um3suaK+79BBxlvkG4VzINEU8EGDBWsPWVhMw1nOHhaspd9NOYre6VfeXcmwp6PceLr1roGACA/FVMsR9K18gmBDF04e1zRqf9AbuGCGpso1+4p2AH+rTSD1gfoU/dLrVd66Ppk+xTH56w5PCN0+6iHebn+2GqM6/nm3I=
  app: pickMeUp
  on:
    repo: NG-SF/pickMeUp
